[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"

[project]
name = "bytewax"
requires-python = ">=3.7"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: System :: Networking",
    "Topic :: System :: Distributed Computing",
]
dependencies = ["dill>=0.3.5"]
extras = ["bigquery", "dynamodb", "dev", "docs", "test"]

[project.optional-dependencies]
bigquery = ["google-cloud-bigquery<=3.3.5"]
dynamodb = ["boto3>=1.15.0"]
kafka = ["confluent-kafka>=2.0.2"]
test = ["pytest==7.1.0", "myst-docutils==0.17.0"]
docs = ["pdoc3==0.10.0"]
dev = [
    "bytewax[bigquery,dynamodb,kafka,test,docs]",
    "black==22.3.0",
    "flake8==4.0.1",
    "isort==5.10.1",
    "pre-commit==2.19.0"
]

[project.urls]
"Source Code" = "https://github.com/bytewax/bytewax"
Issues = "https://github.com/bytewax/bytewax/issues"
Documentation = "https://docs.bytewax.io/"
Changelog = "https://github.com/bytewax/bytewax/blob/main/CHANGELOG.md"

[metadata]
long_description = "file: README.md"
long_description_content_type = "text/markdown"

[tool.pytest.ini_options]
addopts = "-v --doctest-modules"
doctest_optionflags = "NORMALIZE_WHITESPACE"
testpaths = [
    "pytests",
    # TODO: Add back in doctests when we can figure out how to run them without import problems.

    # "pysrc",

    # TODO: Turn back on markdown tests once we stabilize inputs.

    "docs",
]
